# Generated by Django 3.2.9 on 2023-02-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230220_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
    ]
